locals {
  preview_runtime_denied_principals = [
    "principal://iam.googleapis.com/projects/-/serviceAccounts/cloud-run-preview@cdbentley.iam.gserviceaccount.com",
    "principal://iam.googleapis.com/projects/-/serviceAccounts/cloud-run-preview@critical-history-16823277.iam.gserviceaccount.com",
    "principal://iam.googleapis.com/projects/-/serviceAccounts/cloud-run-preview@medlock-1025243085.iam.gserviceaccount.com",
    "principal://iam.googleapis.com/projects/-/serviceAccounts/cloud-run-preview@runsetta.iam.gserviceaccount.com",
  ]

  # IAM deny accepts only the permission names and permission groups published at
  # https://cloud.google.com/iam/docs/deny-permissions-support. Keep this list
  # explicit so provider upgrades and Google support-table drift are reviewable.
  preview_runtime_denied_permissions = [
    # Storage and state.
    "storage.googleapis.com/bucketOperations.*",
    "storage.googleapis.com/buckets.create",
    "storage.googleapis.com/buckets.createTagBinding",
    "storage.googleapis.com/buckets.delete",
    "storage.googleapis.com/buckets.deleteTagBinding",
    "storage.googleapis.com/buckets.enableObjectRetention",
    "storage.googleapis.com/buckets.get",
    "storage.googleapis.com/buckets.getIamPolicy",
    "storage.googleapis.com/buckets.getIpFilter",
    "storage.googleapis.com/buckets.list",
    "storage.googleapis.com/buckets.listEffectiveTags",
    "storage.googleapis.com/buckets.listTagBindings",
    "storage.googleapis.com/buckets.relocate",
    "storage.googleapis.com/buckets.restore",
    "storage.googleapis.com/buckets.setIamPolicy",
    "storage.googleapis.com/buckets.setIpFilter",
    "storage.googleapis.com/buckets.update",
    "storage.googleapis.com/buckets.viewIntelligenceDetails",
    "storage.googleapis.com/folders.*",
    "storage.googleapis.com/hmacKeys.*",
    "storage.googleapis.com/intelligenceConfigs.*",
    "storage.googleapis.com/managedFolders.*",
    "storage.googleapis.com/multipartUploads.*",
    "storage.googleapis.com/objects.*",

    # Secrets and Firestore/Datastore.
    "secretmanager.googleapis.com/*.*",
    "datastore.googleapis.com/backupSchedules.*",
    "datastore.googleapis.com/backups.delete",
    "datastore.googleapis.com/backups.get",
    "datastore.googleapis.com/backups.list",
    "datastore.googleapis.com/databases.bulkDelete",
    "datastore.googleapis.com/databases.clone",
    "datastore.googleapis.com/databases.create",
    "datastore.googleapis.com/databases.delete",
    "datastore.googleapis.com/databases.export",
    "datastore.googleapis.com/databases.get",
    "datastore.googleapis.com/databases.getMetadata",
    "datastore.googleapis.com/databases.import",
    "datastore.googleapis.com/databases.list",
    "datastore.googleapis.com/databases.listEffectiveTags",
    "datastore.googleapis.com/databases.listTagBindings",
    "datastore.googleapis.com/databases.update",
    "datastore.googleapis.com/entities.*",
    "datastore.googleapis.com/insights.*",
    "datastore.googleapis.com/keyVisualizerScans.*",
    "datastore.googleapis.com/namespaces.*",
    "datastore.googleapis.com/operations.*",
    "datastore.googleapis.com/schemas.*",
    "datastore.googleapis.com/statistics.*",
    "datastore.googleapis.com/userCreds.*",
    "firestore.googleapis.com/locations.*",

    # Cloud Run and Artifact Registry.
    "run.googleapis.com/configurations.*",
    "run.googleapis.com/executions.*",
    "run.googleapis.com/instances.*",
    "run.googleapis.com/jobs.*",
    "run.googleapis.com/locations.*",
    "run.googleapis.com/operations.*",
    "run.googleapis.com/prompts.*",
    "run.googleapis.com/revisions.*",
    "run.googleapis.com/routes.*",
    "run.googleapis.com/services.*",
    "run.googleapis.com/tasks.*",
    "run.googleapis.com/workerpools.*",
    "artifactregistry.googleapis.com/attachments.*",
    "artifactregistry.googleapis.com/dockerimages.*",
    "artifactregistry.googleapis.com/files.download",
    "artifactregistry.googleapis.com/files.list",
    "artifactregistry.googleapis.com/files.update",
    "artifactregistry.googleapis.com/files.upload",
    "artifactregistry.googleapis.com/locations.*",
    "artifactregistry.googleapis.com/packages.list",
    "artifactregistry.googleapis.com/packages.update",
    "artifactregistry.googleapis.com/projectconfigs.*",
    "artifactregistry.googleapis.com/projectsettings.*",
    "artifactregistry.googleapis.com/repositories.create",
    "artifactregistry.googleapis.com/repositories.delete",
    "artifactregistry.googleapis.com/repositories.deleteArtifacts",
    "artifactregistry.googleapis.com/repositories.downloadArtifacts",
    "artifactregistry.googleapis.com/repositories.exportArtifacts",
    "artifactregistry.googleapis.com/repositories.get",
    "artifactregistry.googleapis.com/repositories.getIamPolicy",
    "artifactregistry.googleapis.com/repositories.list",
    "artifactregistry.googleapis.com/repositories.setIamPolicy",
    "artifactregistry.googleapis.com/repositories.update",
    "artifactregistry.googleapis.com/repositories.uploadArtifacts",
    "artifactregistry.googleapis.com/rules.*",
    "artifactregistry.googleapis.com/tags.create",
    "artifactregistry.googleapis.com/tags.list",
    "artifactregistry.googleapis.com/versions.get",
    "artifactregistry.googleapis.com/versions.list",
    "artifactregistry.googleapis.com/versions.update",

    # IAM impersonation and policy/control-plane mutation.
    "iam.googleapis.com/serviceAccountKeys.*",
    "iam.googleapis.com/serviceAccounts.actAs",
    "iam.googleapis.com/serviceAccounts.create",
    "iam.googleapis.com/serviceAccounts.delete",
    "iam.googleapis.com/serviceAccounts.disable",
    "iam.googleapis.com/serviceAccounts.enable",
    "iam.googleapis.com/serviceAccounts.get",
    "iam.googleapis.com/serviceAccounts.getAccessToken",
    "iam.googleapis.com/serviceAccounts.getIamPolicy",
    "iam.googleapis.com/serviceAccounts.getOpenIdToken",
    "iam.googleapis.com/serviceAccounts.implicitDelegation",
    "iam.googleapis.com/serviceAccounts.list",
    "iam.googleapis.com/serviceAccounts.setIamPolicy",
    "iam.googleapis.com/serviceAccounts.signBlob",
    "iam.googleapis.com/serviceAccounts.signJwt",
    "iam.googleapis.com/serviceAccounts.undelete",
    "iam.googleapis.com/serviceAccounts.update",
    "iam.googleapis.com/roles.create",
    "iam.googleapis.com/roles.createTagBinding",
    "iam.googleapis.com/roles.delete",
    "iam.googleapis.com/roles.deleteTagBinding",
    "iam.googleapis.com/roles.get",
    "iam.googleapis.com/roles.list",
    "iam.googleapis.com/roles.listEffectiveTags",
    "iam.googleapis.com/roles.listTagBindings",
    "iam.googleapis.com/roles.undelete",
    "iam.googleapis.com/roles.update",
    "iam.googleapis.com/operations.*",
    "iam.googleapis.com/principalaccessboundarypolicies.*",
    "iam.googleapis.com/workloadIdentityPoolManagedIdentities.*",
    "iam.googleapis.com/workloadIdentityPoolNamespaces.*",
    "iam.googleapis.com/workloadIdentityPoolProviderKeys.*",
    "iam.googleapis.com/workloadIdentityPoolProviders.*",
    "iam.googleapis.com/workloadIdentityPools.*",
    "cloudresourcemanager.googleapis.com/projects.*",
    "serviceusage.googleapis.com/consumerpolicy.*",
    "serviceusage.googleapis.com/contentsecuritypolicy.*",
    "serviceusage.googleapis.com/effectivemcppolicy.*",
    "serviceusage.googleapis.com/effectivepolicy.*",
    "serviceusage.googleapis.com/groups.*",
    "serviceusage.googleapis.com/mcppolicy.*",
    "serviceusage.googleapis.com/operations.*",
    "serviceusage.googleapis.com/quotas.*",
    "serviceusage.googleapis.com/services.disable",
    "serviceusage.googleapis.com/services.enable",
    "serviceusage.googleapis.com/services.get",
    "serviceusage.googleapis.com/services.list",
    "serviceusage.googleapis.com/services.use",
    "serviceusage.googleapis.com/values.*",

    # Asset discovery and sensitive logs.
    "cloudasset.googleapis.com/*.*",
    "logging.googleapis.com/buckets.copyLogEntries",
    "logging.googleapis.com/buckets.create",
    "logging.googleapis.com/buckets.createTagBinding",
    "logging.googleapis.com/buckets.delete",
    "logging.googleapis.com/buckets.deleteTagBinding",
    "logging.googleapis.com/buckets.get",
    "logging.googleapis.com/buckets.list",
    "logging.googleapis.com/buckets.listEffectiveTags",
    "logging.googleapis.com/buckets.listTagBindings",
    "logging.googleapis.com/buckets.undelete",
    "logging.googleapis.com/buckets.update",
    "logging.googleapis.com/exclusions.*",
    "logging.googleapis.com/links.*",
    "logging.googleapis.com/locations.*",
    "logging.googleapis.com/logEntries.create",
    "logging.googleapis.com/logEntries.list",
    "logging.googleapis.com/logMetrics.*",
    "logging.googleapis.com/logScopes.*",
    "logging.googleapis.com/logServiceIndexes.*",
    "logging.googleapis.com/logServices.*",
    "logging.googleapis.com/logs.*",
    "logging.googleapis.com/privateLogEntries.*",
    "logging.googleapis.com/queries.*",
    "logging.googleapis.com/settings.get",
    "logging.googleapis.com/sinks.*",
    "logging.googleapis.com/views.*",

    # Load balancing, networking, and certificates. Compute does not publish a
    # service-wide deny group; these are supported resource-family groups.
    "certificatemanager.googleapis.com/*.*",
    "compute.googleapis.com/addresses.*",
    "compute.googleapis.com/backendServices.addSignedUrlKey",
    "compute.googleapis.com/backendServices.create",
    "compute.googleapis.com/backendServices.createTagBinding",
    "compute.googleapis.com/backendServices.delete",
    "compute.googleapis.com/backendServices.deleteSignedUrlKey",
    "compute.googleapis.com/backendServices.deleteTagBinding",
    "compute.googleapis.com/backendServices.get",
    "compute.googleapis.com/backendServices.getIamPolicy",
    "compute.googleapis.com/backendServices.list",
    "compute.googleapis.com/backendServices.listEffectiveTags",
    "compute.googleapis.com/backendServices.listTagBindings",
    "compute.googleapis.com/backendServices.setIamPolicy",
    "compute.googleapis.com/backendServices.setSecurityPolicy",
    "compute.googleapis.com/backendServices.update",
    "compute.googleapis.com/backendServices.use",
    "compute.googleapis.com/forwardingRules.*",
    "compute.googleapis.com/globalForwardingRules.*",
    "compute.googleapis.com/globalAddresses.*",
    "compute.googleapis.com/globalOperations.delete",
    "compute.googleapis.com/globalOperations.getIamPolicy",
    "compute.googleapis.com/globalOperations.list",
    "compute.googleapis.com/globalOperations.setIamPolicy",
    "compute.googleapis.com/globalNetworkEndpointGroups.*",
    "compute.googleapis.com/healthChecks.*",
    "compute.googleapis.com/networkEndpointGroups.*",
    "compute.googleapis.com/networks.*",
    "compute.googleapis.com/projects.*",
    "compute.googleapis.com/regionHealthChecks.*",
    "compute.googleapis.com/regionNetworkEndpointGroups.*",
    "compute.googleapis.com/regionOperations.delete",
    "compute.googleapis.com/regionOperations.getIamPolicy",
    "compute.googleapis.com/regionOperations.list",
    "compute.googleapis.com/regionOperations.setIamPolicy",
    "compute.googleapis.com/regionSslCertificates.*",
    "compute.googleapis.com/regionSslPolicies.*",
    "compute.googleapis.com/regionTargetHttpProxies.*",
    "compute.googleapis.com/regionTargetHttpsProxies.*",
    "compute.googleapis.com/regionUrlMaps.*",
    "compute.googleapis.com/routers.*",
    "compute.googleapis.com/routes.*",
    "compute.googleapis.com/securityPolicies.*",
    "compute.googleapis.com/sslCertificates.*",
    "compute.googleapis.com/sslPolicies.*",
    "compute.googleapis.com/targetHttpProxies.*",
    "compute.googleapis.com/targetHttpsProxies.*",
    "compute.googleapis.com/urlMaps.*",
  ]
}

resource "google_iam_deny_policy" "preview_runtime_supported_deny" {
  parent          = urlencode("cloudresourcemanager.googleapis.com/projects/${var.project_id}")
  name            = "preview-runtime-supported-deny"
  display_name    = "Preview runtime supported-permission deny"
  deletion_policy = "PREVENT"

  rules {
    description = "Deny all supported in-scope access to every standalone preview runtime identity."

    deny_rule {
      denied_principals  = local.preview_runtime_denied_principals
      denied_permissions = local.preview_runtime_denied_permissions
    }
  }
}
