name: Infrastructure

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  infrastructure:
    uses: collinbentley1/platform/.github/workflows/infrastructure.yml@v0.1.0
    with:
      project-id: __PROJECT_ID__
      workload-identity-provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      terraform-service-account: ${{ vars.GCP_TERRAFORM_SERVICE_ACCOUNT }}
